DELETE FROM Farmaceutica;

SET SERVEROUTPUT ON;

DECLARE
    output DBMS_OUTPUT.CHARARR;
    numlines NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica('Farmacia XYZ', '555-1234', 'info@farmaciaxyz.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Richmond Pharmaceuticals, Inc.', '2226076651', 'mmafham0@deliciousdays.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('SJ Creations, Inc.', '6736214329', 'dbouts1@howstuffworks.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Ranbaxy Pharmaceuticals Inc.', '5514368460', 'rpostlewhite2@cnbc.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Parfums Christian Dior', '4103593790', 'lalabastar3@ehow.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Physicians Total Care, Inc.', '8886682291', 'ccoda4@dailymail.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('IGI Labs, Inc.', '5892171655', 'tbartlet5@google.cn'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Apotex Corp.', '5976597178', 'zgowthorpe6@mlb.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('STAT Rx USA LLC', '5955146186', 'avoyce7@amazonaws.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('STAT RX USA LLC', '3243998971', 'mgann8@macromedia.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('BioActive Nutritional, Inc.', '5523657546', 'cangear9@census.gov'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Professional Disposables International, Inc.', '4036874003', 'vshackletona@dropbox.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('ALK-Abello, Inc.', '8399919257', 'rjaqueminetb@macromedia.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('ALK-Abello, Inc.', '5995969397', 'lgrindrodc@economist.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Mylan Pharmaceuticals Inc.', '2407912125', 'jigguldend@issuu.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Physicians Total Care, Inc.', '9637733030', 'jheatone@archive.org'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('SMP Home Medical', '4697913766', 'rshorttf@yandex.ru'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Mylan Institutional Inc.', '9318044886', 'irobinsg@lycos.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Antigen Laboratories, Inc.', '3691367632', 'dmacanultyh@bloglines.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('GeneraMedix', '3941313073', 'dbleezei@mysql.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Team Technologies, Inc', '5291904806', 'sgarmstonj@aboutads.info'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Glenmark Generics Inc., USA', '5132404545', 'zfacchinik@odnoklassniki.ru'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Isis Enterprises LLC DBA: S4 Suncare', '3593507981', 'gferaghl@census.gov'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Target Corporation', '9455229012', 'cpenkethm@java.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Natural Creations, Inc.', '3208854026', 'wtemblettn@ucoz.ru'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Aidarex Pharmaceuticals LLC', '4028043586', 'frissoo@ox.ac.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Western Family Foods Inc', '5764111382', 'gmosdallp@yellowbook.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Dolgencorp Inc', '3439423792', 'hmatyushonokq@e-recht24.de'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('State of Florida DOH Central Pharmacy', '2574522652', 'pmeakingr@disqus.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('CARDINAL HEALTH', '1254468784', 'gsides@deliciousdays.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Graceway Pharmaceuticals, LLC', '6343325830', 'bdoylandt@qq.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Golden State Medical Supply, Inc.', '3164734590', 'dcurzeyu@stumbleupon.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Physicians Total Care, Inc.', '1383413500', 'kfarquarv@flickr.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Major Pharmaceuticals', '6788072440', 'vbostonw@opera.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('NATURE REPUBLIC CO., LTD.', '8145351843', 'kdominikx@fema.gov'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Chain Drug Marketing Association Inc', '3333635218', 'cprettiy@livejournal.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Sandoz Inc', '5302577509', 'osalmonz@uol.com.br'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Zydus Pharmaceuticals (USA) Inc.', '2059749439', 'dgallandre10@ebay.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Hercon Laboratories Corporation', '8888909039', 'rheathwood11@msu.edu'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Bentley Laboratories, LLC', '7347666734', 'boakey12@comsenz.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Actavis Pharma, Inc.', '8297392113', 'hmiere13@chicagotribune.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('REMEDYREPACK INC.', '7924450994', 'llerego14@adobe.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Novartis Consumer Health, Inc.', '2016271744', 'mridings15@hibu.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Teva Parenteral Medicines, Inc', '6208270104', 'cocriane16@ifeng.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('REMEDYREPACK INC.', '8491046620', 'dblees17@amazon.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Lil'' Drug Store Products, Inc', '7729963536', 'rslamaker18@google.nl'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Zydus Pharmaceuticals (USA) Inc.', '4378958764', 'rfarnworth19@bloomberg.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Bristol-Myers Squibb Pharma Company', '6526591524', 'hflatt1a@netvibes.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('G.D. Searle LLC Division of Pfizer Inc', '2178586180', 'mkingett1b@timesonline.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Cardinal Health', '4037067040', 'ctwentyman1c@jugem.jp'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('NCS HealthCare of KY, Inc dba Vangard Labs', '3319741759', 'ilown1d@wix.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('REMEDYREPACK INC.', '3988813533', 'kplace1e@icq.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Clinical Solutions Wholesale', '7029414859', 'lmccahill1f@cargocollective.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Efficient Laboratories, Inc.', '5776138450', 'itinklin1g@xrea.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Uriel Pharmacy Inc.', '2506827176', 'wvallintine1h@pagesperso-orange.fr'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Kmart Corporation', '7515228520', 'zfoakes1i@sfgate.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('APP Pharmaceuticals, LLC', '4272411152', 'sduffitt1j@mit.edu'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('C.D.M.A., Inc', '8319346611', 'ocullingworth1k@about.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('CCA Industries, Inc.', '3712547465', 'rmargiotta1l@clickbank.net'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Exact-Rx, Inc.', '6425581037', 'mmouget1m@google.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('NCS HealthCare of KY, Inc dba Vangard Labs', '5098077394', 'ably1n@lulu.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Kroger Company', '1893428824', 'cpllu1o@desdev.cn'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Deseret Biologicals, Inc.', '6782960343', 'cbattams1p@wufoo.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('American Regent, Inc.', '5303498107', 'morgan1q@reference.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Novartis Pharmaceuticals Corporation', '5506958419', 'rclews1r@berkeley.edu'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Reckitt Benckiser LLC', '7941352338', 'wucchino1s@webeden.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('HOMEOLAB USA INC', '8098853568', 'dmacgillivray1t@ycombinator.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Pedinol Pharmacal, Inc.', '2716088483', 'nlangrish1u@symantec.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Wal-Mart Stores Inc', '1361261742', 'mprattington1v@youtu.be'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Colgate-Palmolive Company', '8054790026', 'jsearight1w@va.gov'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Atlantic Biologicals Corps', '6805655931', 'ilaurie1x@miitbeian.gov.cn'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Benco Dental', '2529074084', 'pjupp1y@google.fr'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('bryant ranch prepack', '4846157483', 'fscougall1z@ucoz.ru'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('BioActive Nutritional, Inc.', '6102950165', 'kvittori20@gmpg.org'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Mutual Pharmaceutical Company, Inc.', '3163774918', 'sburke21@youku.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Aqua Pharmaceuticals', '7537415711', 'bhilldrup22@time.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Wockhardt Limited', '4373695846', 'ghuison23@soundcloud.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('SHISEIDO CO., LTD.', '9456138872', 'hrawkesby24@sbwire.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('MAKEUP ART COSMETICS', '6166263591', 'rwight25@alibaba.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('L Perrigo Company', '4987857932', 'kswadling26@shinystat.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('iNova Pharmaceuticals Pty, Ltd', '7991001406', 'gtink27@jalbum.net'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('CARDINAL HEALTH', '3412795273', 'tmcreynolds28@homestead.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('MAJOR Pharmaceuticals Inc.', '8193351587', 'gseavers29@spiegel.de'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('NATURE REPUBLIC CO., LTD.', '1201859730', 'flynch2a@a8.net'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('REMEDYREPACK INC.', '8354394841', 'hruskin2b@imdb.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('REMEDYREPACK INC.', '5566476043', 'srantoull2c@diigo.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Central McGowan Inc', '8731414974', 'bjecock2d@t-online.de'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Allermed Laboratories, Inc.', '7779959380', 'clandis2e@psu.edu'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Eon Labs, Inc.', '6057137276', 'ddavet2f@biglobe.ne.jp'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Harmon Stores Inc.', '7658530429', 'wyeulet2g@reverbnation.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('NSE Products, Inc.', '8319689844', 'jkirwan2h@fema.gov'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Major Pharmaceuticals', '3934729710', 'dbrunon2i@hc360.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Sagent Pharmaceuticals', '6813846139', 'whein2j@cbc.ca'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Gland Pharma Limited', '1298829197', 'fjanaszkiewicz2k@independent.co.uk'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Boots Retail USA Inc', '7754637955', 'brippin2l@skyrock.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Uriel Pharmacy Inc.', '3363216251', 'bpetrichat2m@google.co.jp'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Western Family Foods Inc', '7108844033', 'lwippermann2n@yale.edu'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('H E B', '8144822436', 'wallsopp2o@dedecms.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Western Family Foods Inc', '6535411800', 'dgaylard2p@wikipedia.org'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Two Hip Consulting, LLC', '3693642315', 'ynormavell2q@jalbum.net'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('Physicians Total Care, Inc.', '1222835314', 'mswalwell2r@wired.com'));
  DBMS_OUTPUT.PUT_LINE('Respuesta: ' || farmacia_insertar.insertar_farmaceutica ('SJ Creations, Inc.', '6736214329', 'dbouts1@howstuffworks.com'));
END;
/

select * from farmaceutica;